//
//  BeerDetailPresenter.swift
//  BeerMarket
//
//  Created by Matheus Cardoso kuhn on 01/07/19.
//  Copyright (c) 2019 MDT. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol BeerDetailPresentationLogic {
    func presentSomething(response: BeerDetail.Something.Response)
}

class BeerDetailPresenter: BeerDetailPresentationLogic {
    
    // MARK: - Variables
    weak var viewController: BeerDetailDisplayLogic?
    
    // MARK: - Do something
    func presentSomething(response: BeerDetail.Something.Response) {
        let viewModel = BeerDetail.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
}
