//
//  BeerListModels.swift
//  BeerMarket
//
//  Created by Matheus Cardoso kuhn on 01/07/19.
//  Copyright (c) 2019 MDT. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum BeerList {
    
    enum BeerModel {
        struct Request {
            let page: Int
        }
        struct Response {
            let newBeers: [Beer]
        }
        struct ViewModel {
            struct DecribedBeer {
                let name: String
                let alcoholByVolume: String
                let imageURL: String
            }
            
            let beers: [DecribedBeer]
        }
    }
    
    enum Selection {
        struct Request {
            let row: Int
        }
    }
    
    enum Image {
        struct Request {
            let row: Int
            let url: String
        }
        struct Response {
            let row: Int
            let image: UIImage
        }
        struct ViewModel {
            let row: Int
            let image: UIImage
        }
    }
    
    enum ErrorModel {
        struct Response {
            let error: Error
        }
        struct ViewModel {
            let error: String
        }
    }
}
