//
//  BeerListRouter.swift
//  BeerMarket
//
//  Created by Matheus Cardoso kuhn on 01/07/19.
//  Copyright (c) 2019 MDT. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol BeerListRoutingLogic {
    //func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol BeerListDataPassing {
    var dataStore: BeerListDataStore? { get }
}

class BeerListRouter: NSObject, BeerListRoutingLogic, BeerListDataPassing {
    
    // MARK: - Variables
    weak var viewController: BeerListViewController?
    var dataStore: BeerListDataStore?
    
    // MARK: - Routing
//    func routeToSomewhere(segue: UIStoryboardSegue?) {
//        if let segue = segue {
//            let destinationVC = segue.destination as! SomewhereViewController
//            var destinationDS = destinationVC.router!.dataStore!
//            passDataToSomewhere(source: dataStore!, destination: &destinationDS)
//        } else {
//            let storyboard = UIStoryboard(name: "Main", bundle: nil)
//            let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
//            var destinationDS = destinationVC.router!.dataStore!
//            passDataToSomewhere(source: dataStore!, destination: &destinationDS)
//            navigateToSomewhere(source: viewController!, destination: destinationVC)
//        }
//    }
    
    // MARK: - Navigation
//    func navigateToSomewhere(source: BeerListViewController, destination: SomewhereViewController) {
//        source.show(destination, sender: nil)
//    }
    
    // MARK: - Passing Data
//    func passDataToSomewhere(source: BeerListDataStore, destination: inout SomewhereDataStore) {
//        destination.name = source.name
//    }
}
