//
//  BeerListWorker.swift
//  BeerMarket
//
//  Created by Matheus Cardoso kuhn on 01/07/19.
//  Copyright (c) 2019 MDT. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Alamofire

class BeerListWorker {
    
    func requestBeerList(request: BeerList.BeerModel.Request, completion: @escaping (_ result: Result<Array<Beer>>) -> Void) {
        ConnectionUtil.request(on: "beers",
                               method: .get,
                               parameters: ["page": request.page]) { (result: Result<Array<Beer>>) in
                                completion(result)
        }
    }
    
    func requestImage(request: BeerList.Image.Request, completion: @escaping (_ result: Result<UIImage>) -> Void) {
        ConnectionUtil.downloadImage(on: request.url) { (result: Result<UIImage>) in
            completion(result)
        }
    }
}
